### ISSUE TITLE
Weird String parsing old syntax

### ISSUE THREAD

**Issue by RussianRonin** [Dreae/sourcepawn-vscode#7] opened 2018-03-23 02:24 UTC
There is a weird issue with the parsing of some strings where it does not pickup the first quote then the whole file will be the string syntax color. Here is an image.

[https://i.imgur.com/6sdZ8u8.png](url)

**Comment by Dreae** [comment] 2019-06-02 03:56
Closing this as a duplicate of #11

**Closed as completed by Dreae** 2019-06-02 03:56 UTC
